### ISSUE TITLE
Error al compilar usando flags

### ISSUE THREAD

**Issue by mananuk** [mojontwins/MK1_Pestecera#1]
Cuando intento usar "if flag" en el script me salta este error al compilar:

Error at file 'my/msc.h::run_script::0::30' line 77: symbol '_read_two_bytes_d_e' not defined
errors insource file mk1.c

![cap1](https://user-images.githubusercontent.com/101019118/158032154-8a225297-3fd0-4907-a9b0-18e547661273.png)

**Comment by mojontwins** [comment]
Había un error en msc3_mk1, al generar código en ensamblador no se respetaba mayúsculas y minúsculas. Esta se nos había pasado porque el motor empezó a desarrollarse en la versión 1.10 de z88dk que no distingue entre mayúsculas y minúsculas en el ensamble, pero z88dk moderno sí lo hace.

Arreglado en el commit https://github.com/mojontwins/MK1_Pestecera/commit/2be1c0dcc4cb8ef2f0a87b8448f3b5636d8a534a en master

¡Gracias!
